apiVersion: v1
kind: ConfigMap
metadata:
  name: community-config
  namespace: app
data:
  DB_HOST: "my-community-prod-mysql.c1664goi0e1d.ap-northeast-2.rds.amazonaws.com"
  DB_USER: "admin"
  DB_NAME: "community_service"
  S3_UPLOADS_BUCKET: "my-community-prod-uploads"
  S3_REGION: "ap-northeast-2"
  ALLOWED_ORIGINS: '["https://my-community.shop"]'
  FRONTEND_URL: "https://my-community.shop"
  TRUSTED_PROXIES: '["10.2.0.0/16"]'
  DEBUG: "false"
  REDIS_URL: "redis://redis-node-0.redis-headless.data.svc.cluster.local:6379"
  UPLOAD_DIR: ""
  TESTING: "false"
