architecture: standalone
auth:
  database: community_service
  username: manager_dev
  # rootPassword, password: --set으로 전달
primary:
  persistence:
    size: 20Gi
    storageClass: local-storage
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  configuration: |-
    [mysqld]
    transaction_isolation = READ-COMMITTED
    character_set_server = utf8mb4
    collation_server = utf8mb4_unicode_ci
    ngram_token_size = 2
    max_connections = 100
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
