apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: app
    name: uploads-pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/uploads
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - <STAGING_WORKER_HOSTNAME>
