apiVersion: v1
kind: ConfigMap
metadata:
  name: community-config
  namespace: app
data:
  DB_HOST: "mysql.data.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "manager_dev"
  DB_NAME: "community_service"
  REDIS_URL: "redis://redis-master.data.svc.cluster.local:6379"
  RATE_LIMIT_BACKEND: "redis"
  WS_BACKEND: "redis"
  ALLOWED_ORIGINS: "https://k8s.my-community.shop"
  EMAIL_BACKEND: "smtp"
  DEBUG: "true"
