apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: community-api-monitor
  namespace: app
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: community-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
