apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: community-secrets
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: community-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: my-community-prod-community-secrets
