apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-fe
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-fe
  template:
    metadata:
      labels:
        app: community-fe
    spec:
      imagePullSecrets:
        - name: ecr-cred
      containers:
        - name: community-fe
          image: 559352512800.dkr.ecr.ap-northeast-2.amazonaws.com/my-community-dev-frontend-k8s:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
