apiVersion: v1
kind: ConfigMap
metadata:
  name: community-config
  namespace: app
data:
  DB_HOST: "mysql.data.svc.cluster.local"
  DB_USER: "manager_dev"
  DB_NAME: "community_service"
  S3_UPLOADS_BUCKET: "my-community-dev-uploads"
  S3_REGION: "ap-northeast-2"
  ALLOWED_ORIGINS: '["https://my-community.shop", "https://k8s.my-community.shop"]'
  TRUSTED_PROXIES: '["10.0.1.160", "10.0.1.23", "10.0.1.12"]'
  TESTING: "true"
  DEBUG: "true"
