apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - mysql.yaml
  - cronjob-mysql-backup.yaml
  - storage/pv-mysql.yaml
  - storage/pv-prometheus.yaml
  - storage/pv-redis.yaml
  - storage/pv-uploads.yaml
  - storage/pvc-uploads.yaml

patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
