apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- mysql.yaml
- cronjob-mysql-backup.yaml
- storage/pv-mysql.yaml
- storage/pv-prometheus.yaml
- storage/pv-redis.yaml
- storage/pv-uploads.yaml
- storage/pvc-uploads.yaml

patches:
- path: configmap-patch.yaml
- path: ingress-patch.yaml

images:
- name: community-backend
  newName: 559352512800.dkr.ecr.ap-northeast-2.amazonaws.com/my-community-dev-backend-k8s
  newTag: sha-d9c081db
- name: community-frontend
  newName: 559352512800.dkr.ecr.ap-northeast-2.amazonaws.com/my-community-dev-frontend-k8s
  newTag: sha-a188c24b
