apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- storage/pv-prometheus.yaml
- storage/pv-redis.yaml
- storage/pv-uploads.yaml
- storage/pvc-uploads.yaml

patches:
- path: configmap-patch.yaml
- path: ingress-patch.yaml

images:
- name: community-backend
  newName: 559352512800.dkr.ecr.ap-northeast-2.amazonaws.com/my-community-staging-backend-k8s
  newTag: sha-80fa7e52
- name: community-frontend
  newName: 559352512800.dkr.ecr.ap-northeast-2.amazonaws.com/my-community-staging-frontend-k8s
  newTag: sha-a935a100
